### ISSUE TITLE
致《燎原》编辑部:

### ISSUE THREAD

**Issue by 2504148899** [muHua-usnnrqffjcqv/muHua-usnnrqffjcqv.github.io#5]
贵刊拜读，深感欣慰，然现不便使用邮箱，故在此留言:

燎原六月刊中《社会主义中国的覆灭》一文 ，错误的写有“黎怀同志至今下落不明”，实际上我在当天下午做毕笔录就已释放。目前一切正常，工作生活均继续进行。万望改正或在下一期刊中注明这一事实。 黎怀

**Comment by muHua-usnnrqffjcqv** [comment]
黎怀同志：
    您好！感谢指正，该错误会在下一刊中予以注明。
此致 敬礼
燎原编辑部

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
2020年6月14日星期日上午9点06分，2504148899 <notifications@github.com> 来信：
